# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, help_text='Optional, exlicitly limit to specific domain.', max_length=64)),
                ('old_path', models.CharField(help_text="This should be an absolute path, excluding the domain name. Example: '/events/search/'.", max_length=255, verbose_name='From path')),
                ('wildcard_match', models.BooleanField(default=False, help_text='Add wildcard (*) to from path', verbose_name='Wildcard mode')),
                ('new_path', models.CharField(help_text='Absolute path, or full url (with http://.../).', max_length=255, verbose_name='To')),
                ('new_site', models.ForeignKey(blank=True, help_text='Optional, automatically insert correct domain name of this site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirect_new_site', to='sites.Site')),
                ('site', models.ForeignKey(blank=True, help_text='Optional, limit redirect to this site.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirect_old_site', to='sites.Site')),
            ],
            options={
                'ordering': ('old_path',),
                'verbose_name': 'Redirect',
                'verbose_name_plural': 'Redirects',
            },
        ),
        migrations.AlterUniqueTogether(
            name='redirect',
            unique_together=set([('site', 'domain', 'old_path')]),
        ),
    ]
