# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-30 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painless_redirects', '0003_auto_20180430_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='keep_querystring',
            field=models.BooleanField(default=False, help_text='Re-applies GET querystring, if any', verbose_name='Keep querystring'),
        ),
        migrations.AddField(
            model_name='redirect',
            name='keep_tree',
            field=models.BooleanField(default=False, help_text='Only applies when wildcard matching enabled', verbose_name='Keep tree'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='wildcard_match',
            field=models.BooleanField(default=False, help_text='Add wildcard (/from/path/*)', verbose_name='Wildcard match'),
        ),
    ]
