# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-30 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painless_redirects', '0005_redirect_permanent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='permanent',
            field=models.BooleanField(default=True, help_text='For temporary fixes, uncheck to use a status code of 302.', verbose_name='Permanent redirect (301)'),
        ),
    ]
