# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-07 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('painless_redirects', '0006_auto_20180830_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='domain',
            field=models.CharField(blank=True, default='', help_text='Optional, exlicitly limit to specific domain', max_length=64),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='keep_querystring',
            field=models.BooleanField(default=False, help_text='Re-applies GET querystring, if any (?page=4&search=banana)', verbose_name='Keep querystring'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='new_path',
            field=models.CharField(help_text='Absolute path, or full url (with http://.../)', max_length=255, verbose_name='To path'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='new_site',
            field=models.ForeignKey(blank=True, help_text='Optional, automatically insert correct domain name of this site', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirect_new_site', to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='old_path',
            field=models.CharField(help_text="Absolute path, excluding the domain name. Example: '/events/search/'", max_length=255, verbose_name='From path'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='permanent',
            field=models.BooleanField(default=True, help_text='For temporary fixes, uncheck to use a status code of 302', verbose_name='Permanent redirect (301)'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Optional, limit redirect to this site', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redirect_old_site', to='sites.Site'),
        ),
    ]
