# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-20 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painless_redirects', '0010_auto_20191213_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='old_path',
            field=models.CharField(help_text="Absolute path, excluding the domain name. Example: '/events/search/'", max_length=800, verbose_name='From path'),
        ),
    ]
