# Generated by Django 2.2.17 on 2020-11-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painless_redirects', '0012_redirecthit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redirecthit',
            options={'ordering': ('-hits',)},
        ),
        migrations.RemoveField(
            model_name='redirect',
            name='hits',
        ),
        migrations.RemoveField(
            model_name='redirecthit',
            name='referrer',
        ),
        migrations.AddField(
            model_name='redirecthit',
            name='last_hit',
            field=models.DateTimeField(auto_now=True, help_text='The last time the URL/Redirect was hit, from this referrer.', null=True),
        ),
        migrations.AddField(
            model_name='redirecthit',
            name='referer',
            field=models.CharField(default='', help_text='Where the hit comes from (ie refering url', max_length=1200, verbose_name='Referer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='redirect',
            name='old_path',
            field=models.CharField(db_index=True, help_text="Absolute path, excluding the domain name. Example: '/events/search/'", max_length=1200, verbose_name='From path'),
        ),
    ]
