# Generated by Django 2.2.17 on 2021-01-23 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painless_redirects', '0014_redirect_ignored'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='redirecthit',
            unique_together={('redirect', 'referer')},
        ),
    ]
