# Generated by Django 2.2.13 on 2021-02-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painless_redirects', '0015_auto_20210123_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirecthit',
            name='last_hit',
            field=models.DateTimeField(auto_now=True, help_text='The last time the URL/Redirect was hit, from this referer.', null=True),
        ),
    ]
