# Generated by Django 3.2.13 on 2023-05-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painless_redirects', '0016_auto_20210223_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='permanent',
            field=models.BooleanField(default=True, help_text='Use status code 301. For temporary fixes, uncheck to use a status code of 302', verbose_name='Permanent'),
        ),
    ]
